### ISSUE TITLE
Unable to install plugins using Twilio CLI in Nodejs

### ISSUE THREAD

**Issue by Arpanks29** [twilio-labs/plugin-serverless#41] opened 2020-10-22 05:32 UTC
Issue Summary
Twilio CLI throwing an error stating local certiifcate in not found. I even installed certificate , still same error occurs.

Code Snippet
twilio plugins:install @twilio-labs/plugin-serverless

paste code here

### Exception/Log
error An unexpected error occurred: "https://registry.yarnpkg.com/@twilio-labs%2fplugin-serverless: unable to get local issuer certificate".
Installing plugin @twilio-labs/plugin-serverless... !
    Error: yarn add @twilio-labs/plugin-serverless@latest --non-interactive
    --mutex=file:C:\Users\ARPANSINGH\.twilio-cli\yarn.lock
    --preferred-cache-folder=C:\Users\ARPANSINGH\.twilio-cli\yarn --check-files exited with code 1

**Comment by philnash** [comment] 2020-10-22 06:28
Sorry to bounce you around various projects, but I believe this is going to have something to do with the Twilio CLI itself, not the serverless plugin.

Could you raise this with https://github.com/twilio/twilio-cli. 

Also, with certificate errors like this the issue may be in your network. Are you behind a corporate firewall or VPN when you try to install the plugin?

**Comment by adamchasetaylor** [comment] 2020-10-26 22:36
@Arpanks29 

Can you set the following environment variable prior to running the command to install the plugin?

`set NODE_OPTIONS=--use-openssl-ca`

This tells the Twilio CLI to use your operating systems certs instead of the default NodeJS certs.

**Comment by Arpanks29** [comment] 2020-10-27 10:02
Tried doing this, still same issue.

**Comment by philnash** [comment] 2020-10-27 22:28
This is being dealt with directly by @adamchasetaylor (and I still think it's an issue somewhere in the main CLI rather than this plugin), so I'm going to close this for now.

**Closed as completed by philnash** 2020-10-27 22:28 UTC

**Comment by dkundel** [comment] 2020-10-27 23:30
Just following up on this. The problem is inside the OClif Plugins Plugin that we are using ([for example Salesforce has the same issue](https://github.com/forcedotcom/lwc-dev-server-feedback/issues/51#issuecomment-647782918)). 
@childish-sambino from our Twilio CLI team opened an issue with them that you can follow here: https://github.com/oclif/plugin-plugins/issues/189

In the meantime a work around should be to delete the `yarn.lock` file inside the `.twilio-cli` directory inside your home directory. So in your case: `C:\Users\ARPANSINGH\.twilio-cli\yarn.lock` and try again.

**Comment by childish-sambino** [comment] 2020-10-28 15:00
Also need to delete the `yarn.lock.lock` folder there.

**Comment by EndsofttechWebSolutions** [comment] 2022-01-07 11:16
I have deleted manually yarn.lock.lock when I tried the again the command twilio plugins:install @twilio-labs/plugin-serverless again yarn.lock.lock recreated. tried it 3x no luck. 

issue facing see below
Installing plugin @twilio-labs/plugin-serverless... failed
    Error: yarn add @twilio-labs/plugin-serverless@latest --non-interactive --mutex=file:C:\Users\user\.twilio-cli\yarn.lock
    --preferred-cache-folder=C:\Users\user\.twilio-cli\yarn --check-files exited with code 1

**Comment by MgHtinLynn** [comment] 2022-03-09 10:05
+ 1

**Comment by philnash** [comment] 2022-03-09 10:45
Hi @MgHtinLynn, are you finding this an issue too? Have you tried the workarounds mentioned above?

**Comment by MgHtinLynn** [comment] 2022-03-09 10:55
hi @philnash 
I tried that way but didn't work till now.

**Comment by philnash** [comment] 2022-03-09 11:03
@MgHtinLynn as this is an old issue that you are commenting on, could I ask you to please fully describe what you are doing and the error that you are getting? Thank you.

**Comment by MgHtinLynn** [comment] 2022-03-09 11:13
Hi @philnash 
Thanks for your information and support.

Currently, I'm trying to integrate for non-native CRM to Twilio Flex

According to docs, I need to create new plugin with react. 
So i tried to install `twilio-cli v2` with `node - v14 `
 I'm trying to install 
`twilio plugins:install @twilio-labs/plugin-flex`
but getting this error 
```
Installing plugin @twilio-labs/plugin-flex... failed
    Error: yarn add @twilio-labs/plugin-flex@latest --non-interactive --mutex=file:/Users/htinlynn/.twilio-cli/yarn.lock
    --preferred-cache-folder=/Users/htinlynn/.twilio-cli/yarn --check-files exited with code 1
```

My Environment 
- Node - v14.17.6
- npm - 8.4.1
- yarn - 2.4.3

Do you have any idea or any solutions to fix it?

**Comment by philnash** [comment] 2022-03-09 11:31
Hey @MgHtinLynn, thanks for the extra information. It turns out that this is not the right repo to report this issue to.

This repo is for the Twilio Serverless toolkit and Serverless plugin, but you are trying to install the Flex plugin. You can find the flex plugin as part of the monorepo here: https://github.com/twilio/flex-plugin-builder. I recommend you open a new issue there with as much information about what is going on.
